language: node_js
cache: npm
node_js:
  - 8
services:
  - postgresql
env:
  - NODE_ENV=travis

before_script:
  - psql -c 'CREATE DATABASE ptam_ci_testing;' -U postgres
  # Run database migrations with schematron
  - git clone https://github.com/rpi-ptam/ptam-service.git
  - cd schematron && cd config && mv travis.json default.json
  - cd .. && npm install && npm run migrate up && cd ..