sudo: false
language: node_js
cache: npm
node_js:
  - 8
services:
  - postgresql
branches:
  only:
    -master

before_script:
  - psql -c 'CREATE DATABASE ptam_ci_testing;' -U postgres
  # Run database migrations with schematron
  - git clone https://github.com/rpi-ptam/schematron.git
  - cd schematron/config && mv travis.json default.json && cd ../../
  - cd schematron && npm install && npm run migrate up && cd ..
script:
  - npm test
  - npm run coveralls