export const STUDENT = "STUDENT";
export const JUDICIAL_BOARD_MEMBER = "JUDICIAL_BOARD_MEMBER";
export const JUDICIAL_BOARD_CHAIR = "JUDICIAL_BOARD_CHAIR";
export const PARKING_OFFICE_OFFICIAL = "PARKING_OFFICE_OFFICIAL";
export const ADMINISTRATOR = "ADMINISTRATOR";